rico/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # /rico/
    url(r'^$', views.index, name='index'),
    # Faults
    url(r'^faults/$', views.FaultIndex.as_view(), name='fault_index'),
    url(r'^faults/new$', views.add_fault, name='add_fault'),
    url(r'^faults/(?P<pk>[0-9]+)/$', views.FaultDetail.as_view(), name='fault_detail'),
    # Issues
    url(r'^issues/$', views.IssueIndex.as_view(), name='issue_index'),
    url(r'^issues/new$', views.add_issue, name='add_issue'),
    url(r'^issues/(?P<pk>[0-9]+)/$', views.IssueDetail.as_view(), name='issue_detail'),
    # Assets
    url(r'^assets/$', views.AssetIndex.as_view(), name='asset_index'),
    url(r'^assets/new$', views.add_asset, name='add_asset'),
    url(r'^assets/(?P<pk>[0-9]+)/$', views.AssetDetail.as_view(), name='asset_detail'),
    # Comments
    url(r'^(?P<object_name>\w+)s/(?P<pk>[0-9]+)/comment/$', views.add_comment, name='add_comment'),
]

zim/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^rico/', include('rico.urls')),
    url(r'^admin/', admin.site.urls),
]

rico/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Comment(models.Model):
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.content


class Fault(models.Model):
    # Attributes
    title = models.CharField(max_length=140)
    description = models.TextField(null=True, blank=True)
    start_time = models.DateTimeField(null=True, blank=True)
    resolved_time = models.DateTimeField(null=True, blank=True)
    status = models.CharField(
        max_length=2, default='AC',
        choices=[('AC', 'Active'),
                 ('IN', 'Inactive'),
                 ('FP', 'False Positive'),
                 ('OB', 'OBE')])
    # Foreign Keys
    comments = models.ManyToManyField(Comment)

    def __str__(self):
        try:
            return str(self.title)
        except NameError:
            return "None"


class Asset(models.Model):
    name = models.CharField(max_length=140)
    faults = models.ManyToManyField(Fault)

    def __str__(self):
        return self.name


class Issue(models.Model):
    # Attributes
    title = models.CharField(max_length=140)
    created_time = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    resolution = models.CharField(
        max_length=2, default='NO',
        choices=[('NO', 'None'),
                 ('MA', 'Manual'),
                 ('GF', 'Ground FDIR'),
                 ('SF', 'Space FDIR'),
                 ('SO', 'Solved'),
                 ('CR', 'Cannot Reproduce'),
                 ('CF', 'Cannot Fix'),
                 ('OB', 'OBE')])
    # Foreign Keys
    faults = models.ManyToManyField(Fault)
    comments = models.ManyToManyField(Comment)

    def __str__(self):
        return self.title

rico/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm
from .models import Fault, Issue, Asset, Comment


class FaultForm(ModelForm):
    class Meta:
        model = Fault
        fields = ('title',
                  'description',
                  'start_time',
                  'resolved_time',
                  'status',
                  )
        exclude = ('comments',)


class IssueForm(ModelForm):
    class Meta:
        model = Issue
        fields = ('title',
                  'description',
                  'resolution',
                  'faults',
                  )
        exclude = ('created_time',
                   'comments',
                   )


class AssetForm(ModelForm):
    class Meta:
        model = Asset
        fields = ('name',)
        exclude = ('faults',)


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        exclude = ('user',)

rico/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import importlib
from datetime import datetime

from django.shortcuts import get_object_or_404, get_list_or_404
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from django.views import generic

from .models import Fault, Asset, Issue
from .forms import FaultForm, IssueForm, AssetForm, CommentForm


def index(request):
    return render(request, 'rico/index.html')


class FaultIndex(generic.ListView):
    template_name = 'faults/index.html'

    def get_queryset(self):
        return Fault.objects.order_by('-id')


class FaultDetail(generic.DetailView):
    model = Fault
    template_name = 'faults/detail.html'


def add_fault(request):
    if request.method == "POST":
        form = FaultForm(request.POST)
        if form.is_valid():
            fault = form.save(commit=False)
            if fault.start_time is None:
                fault.start_time = datetime.now()
            fault.save()
            return redirect('fault_detail', pk=fault.id)
    else:
        form = FaultForm()
    return render(request, 'faults/add_fault.html', {'form': form})


class IssueIndex(generic.ListView):
    template_name = 'issues/index.html'

    def get_queryset(self):
        return Issue.objects.order_by('-id')


class IssueDetail(generic.DetailView):
    model = Issue
    template_name = 'issues/detail.html'


def add_issue(request):
    if request.method == "POST":
        form = IssueForm(request.POST)
        if form.is_valid():
            issue = form.save(commit=False)
            issue.save()
            return redirect('issue_detail', pk=issue.id)
    else:
        form = IssueForm()
    return render(request, 'issues/add_issue.html', {'form': form})


class AssetIndex(generic.ListView):
    template_name = 'assets/index.html'

    def get_queryset(self):
        return Asset.objects.order_by('-id')


class AssetDetail(generic.DetailView):
    model = Asset
    template_name = 'assets/detail.html'


def add_asset(request):
    if request.method == "POST":
        form = AssetForm(request.POST)
        if form.is_valid():
            asset = form.save(commit=False)
            asset.save()
            return redirect('asset_detail', pk=asset.id)
    else:
        form = AssetForm()
    return render(request, 'assets/add_asset.html', {'form': form})


def add_comment(request, object_name, pk):
    rico_models = importlib.import_module('rico.models')
    _object = get_object_or_404(
        getattr(rico_models, object_name.title()), pk=pk)
    if not hasattr(_object, 'comments'):
        return HttpResponseBadRequest(
            "%s does not have comments field" % _object.__name__)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.save()
            _object.comments.add(comment)
            return redirect('%s_detail' % object_name, pk=pk)
    else:
        form = CommentForm()
    return render(request, 'comments/add_comment.html', {'form': form})

rico/templates/assets/add_asset.html
{% block content %}
    <h1>New asset</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

rico/templates/assets/detail.html
{{ asset }}

rico/templates/assets/index.html
{% if asset_list %}
    <ul>
    {% for asset in asset_list %}
        <li><a href="{% url 'asset_detail' asset.id %}">{{ asset.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No assets are available.</p>
{% endif %}

rico/templates/comments/add_comment.html
{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

rico/templates/faults/add_comment_to_fault.html
{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

rico/templates/faults/add_fault.html
{% block content %}
    <h1>New fault</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

rico/templates/faults/detail.html
<h1>Fault {{ fault.id }}: {{ fault.title }}</h1>
<p><strong>Start time: </strong> {{ fault.start_time }}</p>
<p><strong>Resolved time: </strong> {{ fault.resolved_time }}</p>
<p><strong>Status: </strong> {{ fault.get_status_display }}</p>
<p><strong>Description:</strong></p>
<p>{{ fault.description }}</p>
<p><strong>Linked Issues: </strong></p>

{%  for issue in fault.issue_set.all %}
    <p><a href="{% url 'issue_detail' pk=issue.id %}">I-{{ issue.id }}: {{ issue.title }}</a></p>
{% empty %}
    <p>None</p>
{% endfor %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<hr>
<h2>Comments: </h2>
<a class="btn btn-default" href="{% url 'add_comment' object_name='fault' pk=fault.id %}">Add comment</a>
{% for comment in fault.comments.all %}
    <div class="comment">
        <div class="date">{{ comment.timestamp }}</div>
        <strong>{{ comment.user }}</strong>
        <p>{{ comment.content|linebreaks }}</p>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}
<hr>

rico/templates/faults/index.html
{% if fault_list %}
    <ul>
    {% for fault in fault_list %}
        <li><a href="{% url 'fault_detail' fault.id %}">Fault-{{ fault.id }}: {{ fault.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No faults are available.</p>
{% endif %}

rico/templates/issues/add_issue.html
{% block content %}
    <h1>New issue</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

rico/templates/issues/detail.html
<h1>Issue {{ issue.id }}: {{ issue.title }}</h1>
<p><strong>Created time: </strong> {{ issue.created_time }}</p>
<p><strong>Resolution: </strong> {{ issue.get_resolution_display }}</p>
<p><strong>Description: </strong></p>
<p>{{ issue.description }}</p>
<p><strong>Linked Faults: </strong></p>

{%  for fault in issue.faults.all %}
    <p><a href="{% url 'fault_detail' pk=fault.id %}">F-{{ fault.id }}</a></p>
{% empty %}
    <p>None</p>
{% endfor %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<hr>
<h2>Comments: </h2>
<a class="btn btn-default" href="{% url 'add_comment' object_name='issue' pk=issue.id %}">Add comment</a>
{% for comment in issue.comments.all %}
    <div class="comment">
        <div class="date">{{ comment.timestamp }}</div>
        <strong>{{ comment.user }}</strong>
        <p>{{ comment.content|linebreaks }}</p>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}
<hr>

rico/templates/issues/index.html
{% if issue_list %}
    <ul>
    {% for issue in issue_list %}
        <li><a href="{% url 'issue_detail' issue.id %}">{{ issue.id }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No issues are available.</p>
{% endif %}

rico/templates/rico/index.html
<h1> Wireframe Issue / Fault Tracking System </h1>

<p><a href="{% url 'fault_index' %}"> Faults </a></p>
<p><a href="{% url 'issue_index' %}"> Issues </a></p>
<p><a href="{% url 'asset_index' %}"> Assets </a></p>